# file: python/tasks/default.yml

- name: python | Get the distribution specific variables
  include_vars: "{{ansible_os_family}}.yml"

- name: python | Make sure the packages are installed (Debian)
  apt:
    pkg: "{{item}}"
    state: present
  with_items: python_packages
  when: ansible_os_family == "Debian"
  sudo: yes
